runtime: python39
entrypoint: gunicorn -b :$PORT iRecruit_project.wsgi

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.8
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: staticfiles/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
