 #path('api/signup', Registerview.as_view(), name="signup-user"),
    #path('api/email-login', views.login_email_view, name="email-user-login"),
    
   # path('api/login/', LoginView.as_view(), name='login'),
    #path('api/user/', VerifyUser.as_view(), name='login'),
   # path('api/phone-login', views.login_phone_view, name="phone-user-login"),
   # path('api/verify-otp', views.verify_otp_view, name="verify-otp-login"),
    #path('api/upload-resume', UploadResumeView.as_view(), name="upload-resume"),
    #path('api/my-profile', MyProfileView.as_view(), name="view-my-profile"),
   # path('api/create-profile', CreateView.as_view(), name="create-my-profile"),